const express = require('express')
const passport=require("passport")
const cors=require("cors")
const helmet =require("helmet")
const path=require("path")
const app = express()
app.use(cors())
app.use(helmet())
app.use(passport.initialize({}));
require('./auth/auth')(passport);
const port = 3000
const users=require("./routes/user")
const register=require("./routes/register")
const login=require("./routes/login")
const tag=require("./routes/tags")
const image=require("./routes/image")
const advertisement=require("./routes/advertisement")
app.use(express.static(path.join(__dirname,"upload/")))
app.use("/users",users)
app.use("/register",register)
app.use("/login",login)
app.use("/tags",tag)
app.use("/post",advertisement)
app.use("/images",image)
app.get('/', (req, res) => {
  console.log("hello world")
  res.send('Hello World!')
})
app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})